### ISSUE TITLE
[Epic] Task 목록 {Issue Title}

### ISSUE THREAD

**Issue by KWSony** [Opened-Developers/open-mind#13]
# 개요

Task 목록 나열
제시된 요구사항들을 페이지별로 묶었습니다.

# tasks

### 메인 페이지( "/" )

- [ ] 이름 입력 필드 및 "질문 받기" 버튼 구현
- [ ] 버튼 클릭 시 피드 생성 API 호출 및 응답 받은 피드 ID를 활용하여 "/post/{id}/answer" 페이지로 이동

### 질문 목록 페이지 ("/list")

- [ ] 오픈마인드 로고 클릭 시 메인 페이지로 이동하는 기능 구현
- [ ] 현재 페이지 및 정렬 순서 설정 기능 구현
- [ ] 카드 리스트 조회 API 요청 및 응답 처리
- [ ] "답변하러 가기" 버튼 클릭 시 로컬 스토리지 확인 후 페이지 이동 기능 구현
- [ ] PC 화면 대응: 내용 고정, 좌우 여백 조절
- [ ] 태블릿 화면 대응: 네비게이션 여백, 카드 리스트 여백 및 크기 조절
- [ ] 모바일 화면 대응: 상단 영역 여백 및 정렬 조절, 카드 리스트 여백 및 크기 조절

### 개별 피드 페이지 ("/post/{id}/")

- [ ] 답변 완료 여부에 따른 상태 표시 (답변완료 / 미답변)
- [ ] "질문 작성하기" 버튼 클릭 시 모달 창 구현
- [ ] 질문 목록 무한 스크롤 구현
- [ ] 링크 복사, 카카오톡/페이스북 공유 기능 구현
- [ ] 좋아요/싫어요 개수 표시
- [ ] 거절된 질문 표시
- [ ] 질문이 없는 경우 "No_question" 화면 구현
#### 질문 모달창
- [ ] 모달 닫기 기능 구현
- [ ] 질문 내용 입력 시 "질문 보내기" 버튼 활성화 기능 구현

### 답변 하기 페이지 ("/post/{id}/answer")

- [ ] 답변 입력 시 "답변 완료" 버튼 활성화
- [ ] 답변 완료 질문의 "수정하기" 기능 구현
- [ ] 수정 내용이 없는 경우 "수정완료" 버튼 비활성화
- [ ] "삭제하기" 버튼 구현
