### ISSUE TITLE
[Epic] 메인 페이지

### ISSUE THREAD

**Issue by KWSony** [Opened-Developers/open-mind#17]
# 개요
![image](https://github.com/Opened-Developers/open-mind/assets/86594921/abc29379-f530-4d8d-a211-c3500728d86c)

메인 페이지 ( “/” ) 구현

# tasks

- [x] 메인 페이지 내부 요소 배치
- [x] 질문하러 가기" 버튼 구현
- [x] 이름 입력 후 "질문 받기" 버튼 클릭 시 피드 생성 API 호출 및 응답 받은 피드 ID를 활용하여 "/post/{id}/answer" 페이지로 이동 구현
- [x] 로컬 스토리지로 사용자 구분 기능 구현
