### ISSUE TITLE
[Epic] 질문 목록 페이지

### ISSUE THREAD

**Issue by KWSony** [Opened-Developers/open-mind#18]
# 개요
![image](https://github.com/Opened-Developers/open-mind/assets/86594921/0fc74e3c-e504-4782-9da2-a99d55adc419)

질문 목록 페이지 ("/list") 구현 

# tasks

- [ ] 오픈마인드 로고 클릭 시 메인 페이지로 이동하는 기능 구현

- [x] 현재 페이지 및 정렬 순서 설정 기능 구현

- [x] 카드 리스트 조회 API 요청 및 응답 처리

- [x] "답변하러 가기" 버튼 클릭 시 로컬 스토리지 확인 후 페이지 이동 기능 구현

- [x] #14 

- [x] #15 

- [x] #16

**Comment by JiinSeok** [comment]
체크된 항목들은 이미 구현하신 건가요?
